### PR TITLE
use Request method to get first_run

### PR DESCRIPTION
**Pull request by vietdien2005**
I think we should use Request method to get first_run

### CODE REVIEW

**Comment by vietdien2005** [comment]
#311

**Comment by vietdien2005** [comment]
fix #311

**Comment by vietdien2005** [comment]
Laravel change Illuminate\Session\Store::set() to Illuminate\Session\Store::put()
issue [#17397](https://github.com/laravel/framework/issues/17397)

**Comment by daveearley** [comment]
Cheers for this @vietdien2005 :-)

**Comment by ylecuyer** [comment]
@daveearley you should learn how to manage a git project... One PR one feature... git commit messages with meaningful name (no emojis)

**Pull request merged**
