### PR TITLE
Fixing Issue #465 - translatable strings

### PR DESCRIPTION
**Pull request by kerrinhardy**

### CODE REVIEW

**Comment by jeremyquinton** [comment]
@kerrinhardy thanks for both your pull requests. I'm just waiting for this to be updated https://github.com/Attendize/Attendize/pull/486 then I can merge those pull requests.

**Comment by amoldo** [comment]
**few more untranslatable strings:**

```php
// app/Http/Controllers/EventCheckoutController.php:69
message' => 'No tickets selected',
```
```php
// app/Http/Controllers/EventCheckoutController.php:163
'Ticket holder ' . ($i + 1) . '\'s first name is required';
```
```php
// app/Http/Controllers/EventCheckoutController.php:164
'Ticket holder ' . ($i + 1) . '\'s last name is required';
```
```php
// app/Http/Controllers/EventCheckoutController.php:165
'Ticket holder ' . ($i + 1) . '\'s email is required';
```
```php
// app/Http/Controllers/EventCheckoutController.php:166
'Ticket holder ' . ($i + 1) . '\'s email appears to be invalid';
```
```php
// app/Http/Controllers/EventCheckoutController.php:187
'message' => 'No tickets selected',
```
```php
// resources/views/ManageOrganiser/CreateOrganiser.blade.php:70
{!! Form::label('Yes', 'Yes', array('class'=>'control-label', 'id' => 'charge_yes')) !!}
```
```php
// resources/views/ManageOrganiser/CreateOrganiser.blade.php:72
{!! Form::label('No', 'No', array('class'=>'control-label','id' => 'charge_no')) !!}
```

**strings, where {!! trans() !!} needs to be used or html tags removed from string**

```php
// resources/views/ManageEvent/Customize.blade.php:388
@lang("Design.images_provided_by_pixabay")
```
```php
// resources/views/ManageEvent/Modals/ManageOrder.blade.php:14
{{ @trans("ManageEvent.manage_order_title", ["order_ref"=>$order->order_reference]) }}
```
```php
// resources/views/ManageEvent/PrintAttendees.blade.php:22
{{ @trans("Event.n_attendees_for_event", ["num"=>$attendees->count(), "name"=>$event->title, "date"=>$event->start_date->toDayDateTimeString()]) }}
```

**Comment by kerrinhardy** [comment]
@jeremyquinton What's the guiding principle of how the translation files are organised?  Should it be by model, by page that the translation appears on, something else?

**Comment by jeremyquinton** [comment]
@kerrinhardy there really isn't a guiding model as the language files where auto generated using https://github.com/potsky/laravel-localization-helpers.

Wherever you think is most logical for now is fine. 

Can I ask that you update this pull request https://github.com/Attendize/Attendize/pull/494 and https://github.com/Attendize/Attendize/pull/495/files so that the new strings are contained in other language files. 

For example 
'print_attendees_title' => 'needs translations'. Not exactly sure how Laravel behaves when a translation does not exist.

**Comment by jeremyquinton** [comment]
@kerrinhardy are you able to rebase your fork off master. I did a force push which has messed up this Pull Request.

**Comment by etiennemarais** [comment]
@kerrinhardy Please can you let me know if you still have this branch laying around? I'd suggest we make a new pull request to deal with the weird conflicts and force pushes that happened. I am sorry about the double work though :(

I am closing this one in favor of your new PR. Thank you for your contribution, please re-add your changes to a fresh PR with the latest checkout of `next` branch since that has the work for our next release. We appreciate your effort 🙏

**Pull request closed without merging**
