### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by ftbastler**
A German translation for Attendize. 🇩🇪

### CODE REVIEW

**Comment by amoldo** [comment]
Hi, mir ist aufgefallen, dass in den E-Mails größtenteils geduzt wird, in den anderen Strings meist gesiezt. Sollte man vereinheitlichen oder besser gleich in de_formal und de_informal aufteilen.

**Comment by ftbastler** [comment]
Waiting for #465 to translate remaining strings.

**Comment by jeremyquinton** [comment]
@ftbastler please continue translating if you can. I will merge this and then add #465 afterwards

**Comment by ftbastler** [comment]
@jeremyquinton Are you still interested in getting this merged?

**Comment by jeremyquinton** [comment]
@ftbastler yes I would like to get this in. Are you able to rebase the PR or create a new one? I did some git force push commits which makes things look a little ugly.

**Comment by msbt** [comment]
I need attendize in German, anything I could do to get this going?

**Comment by johannac** [comment]
Thanks for your contributions @ftbastler @Modding! I've rebased this with the current HEAD and will merge this now. I have a release planned for June 1st.

**Pull request merged**
