### PR TITLE
Add a single organiser mode

### PR DESCRIPTION
**Pull request by publicarray**
Useful to prevent the public from creating Events/Organisations without authorisation. (should be enabled by default IMHO; but that would break compatibility) 

I would use this where there is only one organisation publishing events and where we don't want to allow the public to create Events/Organisations

(I think this should be enabled by default IMHO; but that would break compatibility)

### CODE REVIEW

**Comment by Bellusterra** [comment]
@publicarray I actually can’t figure out how to allow the public to create events :). It appears that the admin can create users and add organizers, but I don’t see a public facing registeration page.

**Comment by publicarray** [comment]
The public can create new organisation admin accounts and organisers from `/signup` from there users within the organisation can create new events

**Comment by Bellusterra** [comment]
Thank you @publicarray, I must have missed that... I agree the ability to disable that function is a great option to have.

**Comment by etiennemarais** [comment]
@publicarray Thank you for contribution. I am loojing to get this merged into our `next`  branch. Please help with the conflicts? 🙏 The `next` branch has recently undergone a large laravel version upgrade _(6.5.1)_ Please use the new routes file since it has moved

**Comment by publicarray** [comment]
Closing in favour of new pull request on the updated branch `next` #741 🤩

**Pull request closed without merging**
