### PR TITLE
Fix bugs 

### PR DESCRIPTION
**Pull request by publicarray**
Includes #741 and #744 

Due to long standing open PRs. I'll be continuing to work on this branch but likely more for my use cases and won't separate the work into separate PRs, feel to cherry pick if the PR gets too long.

### CODE REVIEW

**Comment by publicarray** [comment]
@johannac I think I can close this since the branches have diverged significantly. I don’t remember but some of these have recently been fixed

**Comment by johannac** [comment]
@publicarray Ok sure, that sounds like a good plan. #744 is resolved now and we can work on #741 as a standalone PR. Was there anything else in here worth keeping/moving to a new PR? What about the ticket CSS stuff?

**Comment by publicarray** [comment]
True, the ticket generation is something I can put into a new PR. Until then I'll leave it open for now.

**Comment by justynpride** [comment]
Is there an eta on when the ticket generation css might be merged? Would love to know what the roadmap / progress is on some of the other pull requests such as the Laravel 7. I'm looking to jump into the project for various use cases I have.

**Comment by publicarray** [comment]
@justynpride I feel you. I've just pushed #798 so this PR can be closed.

Since the virus I'm no longer actively working for the events industry.  #798 is probably my last PR here. Good Luck!

**Comment by justynpride** [comment]
@publicarray So sorry to hear about the change in circumstances. As you note the virus has effectively killed off the events industry at this moment in time. 

A huge thank you for making that new pull request.

**Pull request closed without merging**
