### PR TITLE
Customize date

### PR DESCRIPTION
**Pull request by publicarray**
I've separated the date-time stuff from #471 to this new PR

### CODE REVIEW

**Comment by jeremyquinton** [comment]
@publicarray have a look here at my commit. 

https://github.com/Attendize/Attendize/pull/512/commits/4e75d0abda2babb7a83deec35f4d7cb5bbfed06f

I created another PR off your PR and removed some console.log. I have done some extensive testing and am pretty much ready to merge this. Where those console.logs added by you for debugging?

**Comment by publicarray** [comment]
The split happened at c94b8eaf8b1018eafae87a75ce6b8aa75df34268 I think somehow master and this branch have a different view of what the master branch was. Was there a force push?

**Comment by jeremyquinton** [comment]
@publicarray yes I did a force push which I now regret. Are you able to rebase your PR off master. Not sure if that works after a force push.

**Comment by publicarray** [comment]
[asciicast](https://asciinema.org/a/a05vgubXwGnpUxETfOz5dlTWc)

**Comment by publicarray** [comment]
In the first rebase I deleted the commits from the old master.
`git rebase -i c94b8eaf8b1018eafae87a75ce6b8aa75df34268`

c94b8eaf8b1018eafae87a75ce6b8aa75df34268 is where the split happened

screen shot 2018-11-06 at 7 33 22 am


In the second rebase I added the commits from the new master (the one that's currently on github).
`git rebase --onto upstream/master`

**Comment by jeremyquinton** [comment]
@publicarray thanks for this will test again and hopefully merge soon. Thanks for the video. Wondering if there is a way I fix the other open Pull Requests myself.

**Comment by publicarray** [comment]
@jeremyquinton 😄  Sure, [p4merge](https://www.perforce.com/downloads/visual-merge-tool) is a 3 way merge/diff tool. I mainly use it to solve merge conflicts.

In the future I'm looking into using [Sublime Merge](https://www.sublimemerge.com)  (from the makers of sublime text) instead.

**Pull request merged**
