### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by publicarray**
This PR is a continuation from #476

### CODE REVIEW

**Comment by jeremyquinton** [comment]
@publicarray I was trying to test these changes this morning and the scanner just hangs on iphone 6 chrome safari with a blue screen. What device are you testing on?

**Comment by publicarray** [comment]
I'm on a MacBookPro and I used Google Chrome to test. I've noticed on the laptop sometimes a full system restart is necessary for the isight camera to work. I think there is a bug when my laptop goes to sleep and it stops the isight to start up again. (photo booth dosn't work either)

**Comment by publicarray** [comment]
Did the iPhone 6 work before, without these changes?

**Comment by jeremyquinton** [comment]
@publicarray I'm not sure let me do some testing and then we can get this merge today

**Pull request merged**
