### PR TITLE
Fix Model Factory

### PR DESCRIPTION
**Pull request by publicarray**
This is a generally a prerequisite for unit tests.

### CODE REVIEW

**Comment by publicarray** [comment]
@jeremyquinton do you have time to look at the PRs in the repo? 

Generally If it takes to long I might no longer remember what I did 🤔

**Comment by jeremyquinton** [comment]
@publicarray have set some time aside this week-end to merge all outstanding Pull Requests.

**Comment by publicarray** [comment]
Ah sweet! 🎉

**Comment by publicarray** [comment]
Another way to "fix" PRs it to just `cherrypick` the commits into master. You may need to squash the PRs if there are a large number of (new) commits. Author information will be preserved.

**Comment by jeremyquinton** [comment]
@publicarray thanks very much will merge this and your previous PR this week-end.

**Pull request merged**
